# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
from . import classifier_pb2 as classifier__pb2


class ClassifierStub(object):
    """Service to manage a classifier model of binary leds combinations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.CreateModel = channel.unary_unary(
            '/Classifier/CreateModel',
            request_serializer=classifier__pb2.CreateModelRequest.SerializeToString,
            response_deserializer=classifier__pb2.ModelRepresentation.FromString,
        )
        self.ConsultModel = channel.unary_unary(
            '/Classifier/ConsultModel',
            request_serializer=classifier__pb2.ConsultModelRequest.SerializeToString,
            response_deserializer=classifier__pb2.ConsultModelResponse.FromString,
        )
