# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\"C\n\x12\x43reateModelRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nproportion\x18\x02 \x01(\x02\x12\x0b\n\x03url\x18\x03 \x01(\t\"%\n\x13ModelRepresentation\x12\x0e\n\x06\x64\x65tail\x18\x01 \x01(\t\"1\n\x13\x43onsultModelRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04leds\x18\x02 \x03(\x08\"%\n\x14\x43onsultModelResponse\x12\r\n\x05\x63lass\x18\x01 \x01(\x05\x32\x89\x01\n\x0cModelService\x12:\n\x0b\x43reateModel\x12\x13.CreateModelRequest\x1a\x14.ModelRepresentation\"\x00\x12=\n\x0c\x43onsultModel\x12\x14.ConsultModelRequest\x1a\x15.ConsultModelResponse\"\x00\x62\x06proto3')
)




_CREATEMODELREQUEST = _descriptor.Descriptor(
  name='CreateModelRequest',
  full_name='CreateModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CreateModelRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proportion', full_name='CreateModelRequest.proportion', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='CreateModelRequest.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=81,
)


_MODELREPRESENTATION = _descriptor.Descriptor(
  name='ModelRepresentation',
  full_name='ModelRepresentation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detail', full_name='ModelRepresentation.detail', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=120,
)


_CONSULTMODELREQUEST = _descriptor.Descriptor(
  name='ConsultModelRequest',
  full_name='ConsultModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ConsultModelRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leds', full_name='ConsultModelRequest.leds', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=171,
)


_CONSULTMODELRESPONSE = _descriptor.Descriptor(
  name='ConsultModelResponse',
  full_name='ConsultModelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class', full_name='ConsultModelResponse.class', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=210,
)

DESCRIPTOR.message_types_by_name['CreateModelRequest'] = _CREATEMODELREQUEST
DESCRIPTOR.message_types_by_name['ModelRepresentation'] = _MODELREPRESENTATION
DESCRIPTOR.message_types_by_name['ConsultModelRequest'] = _CONSULTMODELREQUEST
DESCRIPTOR.message_types_by_name['ConsultModelResponse'] = _CONSULTMODELRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateModelRequest = _reflection.GeneratedProtocolMessageType('CreateModelRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEMODELREQUEST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:CreateModelRequest)
  ))
_sym_db.RegisterMessage(CreateModelRequest)

ModelRepresentation = _reflection.GeneratedProtocolMessageType('ModelRepresentation', (_message.Message,), dict(
  DESCRIPTOR = _MODELREPRESENTATION,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:ModelRepresentation)
  ))
_sym_db.RegisterMessage(ModelRepresentation)

ConsultModelRequest = _reflection.GeneratedProtocolMessageType('ConsultModelRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONSULTMODELREQUEST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:ConsultModelRequest)
  ))
_sym_db.RegisterMessage(ConsultModelRequest)

ConsultModelResponse = _reflection.GeneratedProtocolMessageType('ConsultModelResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONSULTMODELRESPONSE,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:ConsultModelResponse)
  ))
_sym_db.RegisterMessage(ConsultModelResponse)



_MODELSERVICE = _descriptor.ServiceDescriptor(
  name='ModelService',
  full_name='ModelService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=213,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateModel',
    full_name='ModelService.CreateModel',
    index=0,
    containing_service=None,
    input_type=_CREATEMODELREQUEST,
    output_type=_MODELREPRESENTATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConsultModel',
    full_name='ModelService.ConsultModel',
    index=1,
    containing_service=None,
    input_type=_CONSULTMODELREQUEST,
    output_type=_CONSULTMODELRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELSERVICE)

DESCRIPTOR.services_by_name['ModelService'] = _MODELSERVICE

# @@protoc_insertion_point(module_scope)
