# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import server.classifier_pb2 as classifier__pb2


class ClassifierStub(object):
  """Service to manage a classifier model of binary leds combinations.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateModel = channel.unary_unary(
        '/Classifier/CreateModel',
        request_serializer=classifier__pb2.CreateModelRequest.SerializeToString,
        response_deserializer=classifier__pb2.ModelRepresentation.FromString,
        )
    self.ConsultModel = channel.unary_unary(
        '/Classifier/ConsultModel',
        request_serializer=classifier__pb2.ConsultModelRequest.SerializeToString,
        response_deserializer=classifier__pb2.ConsultModelResponse.FromString,
        )


class ClassifierServicer(object):
  """Service to manage a classifier model of binary leds combinations.
  """

  def CreateModel(self, request, context):
    """Request to create of a new model.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConsultModel(self, request, context):
    """Consult a model for the class of a leds sequence.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClassifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateModel': grpc.unary_unary_rpc_method_handler(
          servicer.CreateModel,
          request_deserializer=classifier__pb2.CreateModelRequest.FromString,
          response_serializer=classifier__pb2.ModelRepresentation.SerializeToString,
      ),
      'ConsultModel': grpc.unary_unary_rpc_method_handler(
          servicer.ConsultModel,
          request_deserializer=classifier__pb2.ConsultModelRequest.FromString,
          response_serializer=classifier__pb2.ConsultModelResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Classifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
